// KERN — AI Reading Intelligence for Deep Learners
// Inspired by:
//   - Linear (darkmodedesign.com): deep-black ambient product previews, rounded grotesque at scale
//   - Obsidian (darkmodedesign.com): violet accent on #1a1a1a, knowledge-graph metaphor
//   - 108 Supply (darkmodedesign.com): editorial sparse type, counted items ("027 templates")
//   - minimal.gallery / KOMETA: bold type as primary design element
// Theme: DARK — near-black with violet+teal, focused "reading mode" aesthetic
// Generated by RAM Design Heartbeat — 2026-03-28

const fs = require('fs');

const W = 390, H = 844;
const PAD = 24;

const C = {
  bg:        '#0C0C10',
  surface:   '#131318',
  surface2:  '#1C1C26',
  border:    '#252532',
  text:      '#E8E4F0',
  muted:     'rgba(200,192,228,0.45)',
  dim:       'rgba(200,192,228,0.14)',
  accent:    '#7B5EA7',
  accentBr:  '#9B7EC8',
  teal:      '#3ECFCF',
  tealDim:   'rgba(62,207,207,0.14)',
  violetDim: 'rgba(123,94,167,0.18)',
  violetMid: 'rgba(123,94,167,0.40)',
  red:       '#E05C5C',
  amber:     '#E8A040',
  green:     '#4EC994',
};

function rect(x, y, w, h, fill, opts = {}) {
  return { type: 'RECTANGLE', x, y, width: Math.max(w, 0.5), height: Math.max(h, 0.5), fill, cornerRadius: opts.r || 0, opacity: opts.opacity || 1, stroke: opts.stroke || null, strokeWidth: opts.sw || 0 };
}

function text(content, x, y, opts = {}) {
  return {
    type: 'TEXT', x, y, content,
    fontSize: opts.size || 14,
    fontFamily: opts.font || 'Inter',
    fontWeight: opts.weight || '400',
    fill: opts.color || C.text,
    letterSpacing: opts.ls !== undefined ? opts.ls : -0.2,
    lineHeight: opts.lh || 1.35,
    width: opts.w || 300,
    align: opts.align || 'left',
    opacity: opts.opacity || 1,
  };
}

function line(x1, y1, x2, y2, color, opts = {}) {
  return { type: 'LINE', x: x1, y: y1, points: [{ x: 0, y: 0 }, { x: x2 - x1, y: y2 - y1 }], stroke: color, strokeWidth: opts.sw || 1, opacity: opts.opacity || 1 };
}

function pill(label, x, y, fill, textColor, opts = {}) {
  const w = opts.w || Math.max(label.length * 6.5 + 18, 32);
  const h = opts.h || 22;
  return {
    type: 'GROUP', x, y,
    children: [
      rect(0, 0, w, h, fill, { r: h / 2 }),
      text(label, 9, (h - 13) / 2 + 1, { size: 10, weight: '600', color: textColor, ls: 0.2, w: w - 18 }),
    ],
  };
}

function statusBar() {
  return {
    type: 'GROUP', x: 0, y: 0,
    children: [
      rect(0, 0, W, 48, C.bg),
      text('9:41', PAD, 16, { size: 15, weight: '600', color: C.text, ls: 0, w: 60 }),
      text('●●  ▲  ▌▌', W - PAD - 72, 16, { size: 11, weight: '500', color: C.muted, ls: 0.8, w: 72, align: 'right' }),
    ],
  };
}

function navBar(active) {
  const tabs = [
    { label: 'Home',   icon: '⌂', x: 0   },
    { label: 'Read',   icon: '◫', x: 78  },
    { label: 'Notes',  icon: '◈', x: 156 },
    { label: 'Graph',  icon: '◎', x: 243 },
    { label: 'Review', icon: '↻', x: 321 },
  ];
  const items = [rect(0, 0, W, 72, C.surface), line(0, 0, W, 0, C.border, { sw: 1 })];
  tabs.forEach((tab, i) => {
    const isActive = i === active;
    items.push(
      text(tab.icon, tab.x + 24, 12, { size: 17, color: isActive ? C.accentBr : C.muted, w: 30, align: 'center' }),
      text(tab.label, tab.x + 6, 36, { size: 9, weight: isActive ? '700' : '400', color: isActive ? C.accentBr : C.muted, ls: 0.3, w: 66, align: 'center' }),
    );
    if (isActive) items.push(rect(tab.x + 22, 58, 35, 2, C.accentBr, { r: 1 }));
  });
  return { type: 'GROUP', x: 0, y: H - 72, children: items };
}

function card(x, y, w, h, children, opts = {}) {
  return {
    type: 'GROUP', x, y,
    children: [
      rect(0, 0, w, h, C.surface, { r: opts.r || 12, stroke: C.border, sw: 1 }),
      ...children,
    ],
  };
}

function accentCard(x, y, w, h, accentColor, children, opts = {}) {
  return {
    type: 'GROUP', x, y,
    children: [
      rect(0, 0, w, h, C.surface, { r: opts.r || 12, stroke: accentColor, sw: 1 }),
      rect(0, 0, 3, h, accentColor, { r: 2 }),
      ...children,
    ],
  };
}

// ── SCREEN 1: HOME ──────────────────────────────────────────────

function screen1() {
  const els = [];
  els.push(rect(0, 0, W, H, C.bg));
  els.push(statusBar());

  // Wordmark — typographic, spare (108 Supply influence)
  els.push(text('kern', PAD, 60, { size: 30, weight: '700', color: C.text, ls: -1.5, w: 120 }));
  els.push(pill('⌘ K', W - PAD - 44, 68, C.surface2, C.muted, { w: 44, h: 24 }));

  // Greeting
  els.push(text('Good morning, Rakis.', PAD, 104, { size: 15, weight: '400', color: C.muted, ls: -0.2, w: 290 }));

  // Streak card — editorial count display
  const sparkColors = Array.from({ length: 14 }, (_, i) =>
    i === 13 ? C.accentBr : i > 9 ? C.violetMid : C.violetDim
  );
  els.push(
    card(PAD, 130, W - PAD * 2, 72, [
      text('🔥', 16, 17, { size: 20, w: 28 }),
      text('14', 46, 15, { size: 28, weight: '700', color: C.text, ls: -1.5, w: 56 }),
      text('day streak', 46, 50, { size: 10, color: C.muted, ls: 0.2, w: 80 }),
      ...sparkColors.map((c, i) => rect(118 + i * 14, 26, 10, 10, c, { r: 5 })),
    ]),
  );

  // AI Resurface (teal card — Obsidian's accent-on-dark influence)
  els.push(text('AI RESURFACED', PAD, 218, { size: 10, weight: '700', color: C.teal, ls: 1.2, w: 200 }));
  els.push(
    accentCard(PAD, 236, W - PAD * 2, 90, C.teal, [
      pill('◈ connection', 14, 14, C.tealDim, C.teal, { w: 96, h: 20 }),
      text('"The map is not the territory" — your Korzybski highlight now links to 3 notes on LLM hallucination.', 14, 44, { size: 12, color: C.text, ls: -0.1, lh: 1.5, w: W - PAD * 2 - 28 }),
    ]),
  );

  // Queue
  els.push(text('READING QUEUE', PAD, 344, { size: 10, weight: '700', color: C.muted, ls: 1.2, w: 180 }));
  els.push(pill('3 unread', W - PAD - 58, 342, C.violetDim, C.accentBr, { w: 58, h: 20 }));

  const queue = [
    { title: 'The Unreasonable Effectiveness of RNNs', src: 'karpathy.github.io', pct: 0,   tag: 'AI',      tc: C.teal,     tb: C.tealDim },
    { title: 'Against Metrics — Goodhart\'s Law',       src: 'aeon.co',          pct: 62,  tag: 'Systems', tc: C.accentBr, tb: C.violetDim },
    { title: 'How to Read a Book (Adler, Ch 12)',        src: 'Book · Annotated', pct: 100, tag: '✓ Done',  tc: C.green,    tb: 'rgba(78,201,148,0.12)' },
  ];
  queue.forEach((item, i) => {
    const y = 370 + i * 80;
    const barW = Math.max(4, ((W - PAD * 2) * item.pct) / 100);
    els.push(
      card(PAD, y, W - PAD * 2, 70, [
        rect(0, 0, W - PAD * 2, 2, C.border, { r: 1 }),
        rect(0, 0, barW, 2, item.pct === 100 ? C.green : C.accentBr, { r: 1 }),
        text(item.title, 14, 14, { size: 13, weight: '500', color: C.text, ls: -0.2, w: W - PAD * 2 - 100, lh: 1.4 }),
        text(item.src, 14, 48, { size: 10, color: C.muted, ls: 0, w: 170 }),
        pill(item.tag, W - PAD * 2 - 12 - Math.max(item.tag.length * 6.5 + 18, 44), 46, item.tb, item.tc, { h: 20 }),
      ]),
    );
  });

  els.push(navBar(0));
  return { name: 'Home — Reading Queue', width: W, height: H, elements: els };
}

// ── SCREEN 2: READER ────────────────────────────────────────────

function screen2() {
  const els = [];
  els.push(rect(0, 0, W, H, '#0A0A0E'));

  // Minimal reader top bar
  els.push(rect(0, 0, W, 52, '#0A0A0E'));
  els.push(text('←', PAD, 16, { size: 18, weight: '300', color: C.muted, w: 30 }));
  els.push(text('The Unreasonable Effectiveness of RNNs', PAD + 28, 18, { size: 11, weight: '500', color: C.muted, ls: -0.1, w: W - PAD * 2 - 54 }));
  els.push(text('⋯', W - PAD - 14, 18, { size: 16, color: C.muted, w: 18, align: 'right' }));

  // Reading progress bar
  els.push(rect(0, 52, W, 2, C.border));
  els.push(rect(0, 52, W * 0.38, 2, C.accentBr));
  els.push(text('38%', W - PAD - 28, 58, { size: 10, weight: '500', color: C.accentBr, ls: 0, w: 28 }));

  els.push(text('karpathy.github.io  ·  Nov 21, 2015', PAD, 72, { size: 10, color: C.muted, ls: 0.1, w: 280 }));

  // Big editorial article title (Linear hero type influence)
  els.push(text('The Unreasonable\nEffectiveness of\nRecurrent Neural\nNetworks', PAD, 94, { size: 26, weight: '700', color: C.text, ls: -1.0, lh: 1.2, w: W - PAD * 2 }));

  // Body text
  els.push(text("There's something magical about Recurrent Neural Networks (RNNs). I still remember when I trained my first recurrent network for Image Captioning. Within a few dozen minutes of training my first baby model...", PAD, 228, { size: 14, color: C.text, ls: -0.1, lh: 1.65, w: W - PAD * 2, opacity: 0.88 }));

  // Highlighted passage — violet glow
  els.push(rect(PAD - 4, 348, W - PAD * 2 + 8, 54, C.violetDim, { r: 4 }));
  els.push(rect(PAD - 4, 348, 3, 54, C.accentBr, { r: 2 }));
  els.push(text("...the results were so immediately interesting, I felt compelled to investigate them further by writing this post.", PAD + 6, 356, { size: 14, color: C.text, ls: -0.1, lh: 1.55, w: W - PAD * 2 - 10 }));

  // AI annotation bubble (teal)
  els.push(rect(PAD, 412, W - PAD * 2, 46, C.tealDim, { r: 8 }));
  els.push(text('◈', PAD + 10, 424, { size: 13, color: C.teal, w: 18 }));
  els.push(text('Kern connected this to "Wonder as epistemic signal" from 3 days ago', PAD + 28, 421, { size: 11, color: C.teal, ls: -0.1, lh: 1.42, w: W - PAD * 2 - 40 }));

  // More body
  els.push(text("I'll try to convince you that this is true with three relatively minor examples. The first will be a character-level language model and the second and third will be handwriting generation.", PAD, 470, { size: 14, color: C.text, ls: -0.1, lh: 1.65, w: W - PAD * 2, opacity: 0.88 }));

  // Second highlight
  els.push(rect(PAD - 4, 536, W - PAD * 2 + 8, 36, C.violetDim, { r: 4 }));
  els.push(rect(PAD - 4, 536, 3, 36, C.accentBr, { r: 2 }));
  els.push(text("...the network was able to learn the structure of language and generate reasonably coherent text.", PAD + 6, 544, { size: 14, color: C.text, ls: -0.1, lh: 1.55, w: W - PAD * 2 - 10 }));

  // Floating action bar (reader mode — no full nav)
  els.push(rect(PAD + 16, H - 96, W - PAD * 2 - 32, 52, C.surface2, { r: 26, stroke: C.border, sw: 1 }));
  [
    { icon: '✦', label: 'Note',  dx: 18  },
    { icon: '◈', label: 'Link',  dx: 90  },
    { icon: '◫', label: 'Copy',  dx: 163 },
    { icon: '⊞', label: 'Share', dx: 237 },
  ].forEach(a => {
    els.push(text(a.icon, PAD + 16 + a.dx, H - 96 + 10, { size: 14, color: C.muted, w: 26, align: 'center' }));
    els.push(text(a.label, PAD + 14 + a.dx, H - 96 + 30, { size: 9, weight: '500', color: C.muted, ls: 0.2, w: 30, align: 'center' }));
  });

  return { name: 'Reader — Immersive Mode', width: W, height: H, elements: els };
}

// ── SCREEN 3: HIGHLIGHTS FEED ────────────────────────────────────

function screen3() {
  const els = [];
  els.push(rect(0, 0, W, H, C.bg));
  els.push(statusBar());

  els.push(text('Highlights', PAD, 60, { size: 24, weight: '700', color: C.text, ls: -0.8, w: 200 }));
  els.push(text('127 total · 6 AI links found', PAD, 90, { size: 12, color: C.muted, ls: -0.1, w: 280 }));

  // Filter chips
  [
    { label: 'All',       active: false, x: PAD,       w: 36  },
    { label: 'Connected', active: true,  x: PAD + 46,  w: 80  },
    { label: 'Reviewed',  active: false, x: PAD + 136, w: 70  },
    { label: 'Orphaned',  active: false, x: PAD + 216, w: 68  },
  ].forEach(f => {
    els.push(rect(f.x, 108, f.w, 26, f.active ? C.accent : C.surface2, { r: 13 }));
    els.push(text(f.label, f.x + f.w / 2 - f.label.length * 3.1, 114, { size: 11, weight: f.active ? '700' : '500', color: f.active ? '#fff' : C.muted, ls: 0.2, w: f.w }));
  });

  const items = [
    {
      quote: '"The map is not the territory. The word is not the thing it represents."',
      src:  'Against Metrics — Aeon',
      conn: 3, tags: ['epistemology', 'LLMs'],
      age:  '2 days ago',
    },
    {
      quote: '"Wonder is not just emotion — it\'s an epistemic signal pointing toward uncharted territory."',
      src:  'Wonder & Learning — personal note',
      conn: 2, tags: ['metacognition'],
      age:  '3 days ago',
    },
    {
      quote: '"Spaced repetition is less a memory technique and more a discipline of attention."',
      src:  'How to Read a Book — Adler',
      conn: 1, tags: ['learning'],
      age:  '5 days ago',
    },
  ];

  items.forEach((item, i) => {
    const y = 148 + i * 170;
    const connColor = item.conn > 0 ? C.teal : C.border;
    els.push(
      accentCard(PAD, y, W - PAD * 2, 156, connColor, [
        ...(item.conn > 0 ? [
          rect(14, 14, 90, 20, C.tealDim, { r: 10 }),
          text(`◈ ${item.conn} connection${item.conn > 1 ? 's' : ''}`, 22, 18, { size: 10, weight: '600', color: C.teal, ls: 0.2, w: 78 }),
        ] : []),
        text(item.quote, 14, item.conn > 0 ? 44 : 18, { size: 13, color: C.text, ls: -0.1, lh: 1.5, w: W - PAD * 2 - 28 }),
        text(item.src, 14, item.conn > 0 ? 110 : 84, { size: 10, color: C.muted, ls: 0, w: 200 }),
        ...item.tags.map((t, ti) => pill(t, 14 + ti * (t.length * 6 + 28), item.conn > 0 ? 128 : 102, C.violetDim, C.accentBr, { h: 20 })),
        text(item.age, W - PAD * 2 - 14 - 64, item.conn > 0 ? 130 : 104, { size: 10, color: C.muted, ls: 0, w: 64, align: 'right' }),
      ]),
    );
  });

  els.push(navBar(2));
  return { name: 'Highlights — Connected Feed', width: W, height: H, elements: els };
}

// ── SCREEN 4: KNOWLEDGE GRAPH ────────────────────────────────────

function screen4() {
  const els = [];
  els.push(rect(0, 0, W, H, '#080810'));
  els.push(statusBar());

  els.push(text('Knowledge Graph', PAD, 60, { size: 22, weight: '700', color: C.text, ls: -0.8, w: 260 }));
  els.push(text('14 concepts · 27 links', PAD, 88, { size: 12, color: C.muted, ls: -0.1, w: 200 }));

  const GX = PAD, GY = 108, GW = W - PAD * 2, GH = 460;
  els.push(rect(GX, GY, GW, GH, '#0B0B14', { r: 16, stroke: C.border, sw: 1 }));

  // Ambient dot grid
  for (let gx = GX + 14; gx < GX + GW - 8; gx += 26) {
    for (let gy = GY + 14; gy < GY + GH - 8; gy += 26) {
      els.push(rect(gx, gy, 2, 2, C.dim, { r: 1 }));
    }
  }

  const nodes = [
    { id: 'epistemology', x: 195, y: 220, r: 22, color: C.accent,   label: 'Epistemology' },
    { id: 'llm',          x: 108, y: 300, r: 16, color: C.teal,     label: 'LLMs'         },
    { id: 'wonder',       x: 286, y: 280, r: 14, color: C.accentBr, label: 'Wonder'       },
    { id: 'maps',         x: 148, y: 388, r: 13, color: C.amber,    label: 'Models'       },
    { id: 'memory',       x: 302, y: 384, r: 12, color: C.green,    label: 'Memory'       },
    { id: 'rnn',          x: 76,  y: 418, r: 10, color: C.teal,     label: 'RNNs'         },
    { id: 'goodhart',     x: 244, y: 188, r: 10, color: C.amber,    label: "Goodhart's"   },
    { id: 'attention',    x: 334, y: 162, r: 10, color: C.green,    label: 'Attention'    },
  ];

  const edges = [
    ['epistemology','llm'],['epistemology','wonder'],['epistemology','maps'],
    ['llm','rnn'],['llm','maps'],['wonder','memory'],['wonder','attention'],
    ['maps','goodhart'],['memory','rnn'],['goodhart','epistemology'],['attention','llm'],
  ];

  const nodeMap = Object.fromEntries(nodes.map(n => [n.id, n]));
  edges.forEach(([a, b]) => {
    const na = nodeMap[a], nb = nodeMap[b];
    if (!na || !nb) return;
    const isTeal = (a === 'llm' || b === 'llm' || a === 'rnn' || b === 'rnn');
    els.push(line(GX + na.x, GY + na.y, GX + nb.x, GY + nb.y, isTeal ? 'rgba(62,207,207,0.22)' : 'rgba(123,94,167,0.22)', { sw: 1 }));
  });

  nodes.forEach(n => {
    const isSel = n.id === 'epistemology';
    // Glow
    const glowFill = n.color + '1F'; // ~12% alpha
    els.push(rect(GX + n.x - n.r * 2, GY + n.y - n.r * 2, n.r * 4, n.r * 4, glowFill, { r: n.r * 2 }));
    // Circle
    els.push(rect(GX + n.x - n.r, GY + n.y - n.r, n.r * 2, n.r * 2, isSel ? n.color : C.surface2, { r: n.r, stroke: n.color, sw: isSel ? 2 : 1 }));
    // Label
    els.push(text(n.label, GX + n.x - 44, GY + n.y + n.r + 5, { size: 9, weight: isSel ? '700' : '400', color: isSel ? n.color : C.muted, ls: 0.1, w: 88, align: 'center' }));
  });

  // Selected node detail
  els.push(
    card(PAD, GY + GH + 8, W - PAD * 2, 80, [
      rect(0, 0, 3, 80, C.accent, { r: 2 }),
      text('Epistemology', 14, 12, { size: 14, weight: '700', color: C.text, ls: -0.3, w: 180 }),
      text('8 highlights · 5 connections · 3 orphaned', 14, 34, { size: 11, color: C.muted, ls: 0, w: W - PAD * 2 - 90 }),
      text('Tap to explore →', 14, 56, { size: 11, weight: '500', color: C.accentBr, ls: 0, w: 140 }),
      rect(W - PAD * 2 - 46, 12, 42, 42, C.violetDim, { r: 21 }),
      text('8', W - PAD * 2 - 27, 24, { size: 16, weight: '700', color: C.accentBr, ls: -0.5, w: 14, align: 'center' }),
    ]),
  );

  els.push(navBar(3));
  return { name: 'Graph — Knowledge Map', width: W, height: H, elements: els };
}

// ── SCREEN 5: DAILY REVIEW ───────────────────────────────────────

function screen5() {
  const els = [];
  els.push(rect(0, 0, W, H, C.bg));
  els.push(statusBar());

  els.push(text('Daily Review', PAD, 60, { size: 24, weight: '700', color: C.text, ls: -0.8, w: 240 }));
  els.push(text('Sat, 28 Mar 2026', PAD, 90, { size: 12, color: C.muted, ls: -0.1, w: 220 }));

  // Session progress
  els.push(rect(PAD, 112, W - PAD * 2, 4, C.surface2, { r: 2 }));
  els.push(rect(PAD, 112, (W - PAD * 2) * 0.4, 4, C.accentBr, { r: 2 }));
  els.push(text('2 of 5', W - PAD - 40, 112, { size: 10, weight: '500', color: C.muted, ls: 0, w: 40, align: 'right' }));

  // Main review card
  els.push(rect(PAD, 130, W - PAD * 2, 316, C.surface, { r: 16, stroke: C.border, sw: 1 }));
  els.push(rect(PAD, 130, W - PAD * 2, 4, C.accent, { r: 2 })); // accent top stripe

  els.push(pill('Against Metrics — Aeon', PAD + 16, 148, C.violetDim, C.accentBr, { w: 190, h: 24 }));
  els.push(text('"The map is not the territory. The word is not the thing it represents."', PAD + 16, 184, { size: 18, weight: '600', color: C.text, ls: -0.5, lh: 1.45, w: W - PAD * 2 - 32 }));

  els.push(line(PAD + 16, 292, W - PAD - 16, 292, C.border, { sw: 1 }));

  els.push(text('◈  KERN CONNECTION', PAD + 16, 302, { size: 10, weight: '700', color: C.teal, ls: 0.8, w: 200 }));
  els.push(text("Aligns with your 3 highlights on Goodhart's Law — all explore how representation diverges from reality.", PAD + 16, 322, { size: 12, color: C.muted, ls: -0.1, lh: 1.5, w: W - PAD * 2 - 32 }));

  // SRS buttons
  [
    { label: 'Again', bg: '#2A1515', color: C.red   },
    { label: 'Hard',  bg: '#2A2410', color: C.amber  },
    { label: 'Good',  bg: '#112A1E', color: C.green  },
    { label: 'Easy',  bg: C.violetDim, color: C.accentBr },
  ].forEach((b, i) => {
    const bw = (W - PAD * 2 - 24) / 4;
    const bx = PAD + i * (bw + 8);
    els.push(rect(bx, 460, bw, 40, b.bg, { r: 10 }));
    els.push(text(b.label, bx, 472, { size: 12, weight: '600', color: b.color, ls: 0.2, w: bw, align: 'center' }));
  });

  // Stats
  els.push(
    card(PAD, 514, W - PAD * 2, 66, [
      ...[
        { label: 'Due',       value: '5'   },
        { label: 'Reviewed',  value: '2'   },
        { label: 'Streak',    value: '14d' },
        { label: 'Retention', value: '91%' },
      ].map((s, i) => [
        text(s.value, 14 + i * 82, 12, { size: 18, weight: '700', color: i === 3 ? C.green : C.text, ls: -0.6, w: 56 }),
        text(s.label,  14 + i * 82, 38, { size: 9, color: C.muted, ls: 0.1, w: 66 }),
      ]).flat(),
    ]),
  );

  // Today's synthesis prompt
  els.push(rect(PAD, 594, W - PAD * 2, 72, C.tealDim, { r: 12 }));
  els.push(text('◈', PAD + 16, 610, { size: 14, color: C.teal, w: 18 }));
  els.push(text('TODAY\'S SYNTHESIS', PAD + 36, 608, { size: 10, weight: '700', color: C.teal, ls: 0.8, w: 200 }));
  els.push(text("All 5 cards share a thread: how representations diverge from reality. Kern suggests a synthesis note.", PAD + 36, 628, { size: 11, color: C.teal, ls: -0.1, lh: 1.45, w: W - PAD * 2 - 52 }));

  els.push(navBar(4));
  return { name: 'Review — Spaced Repetition', width: W, height: H, elements: els };
}

// ── WRITE ────────────────────────────────────────────────────────

const pen = {
  version: '2.8',
  name: 'KERN — AI Reading Intelligence',
  description: 'Dark-mode reading + knowledge tool for researchers. Violet+teal accent, graph view, AI-surfaced connections.',
  screens: [screen1(), screen2(), screen3(), screen4(), screen5()],
};

fs.writeFileSync('kern.pen', JSON.stringify(pen, null, 2));
console.log(`✓ kern.pen written — ${pen.screens.length} screens`);
console.log(`  Size: ${(fs.statSync('kern.pen').size / 1024).toFixed(1)} KB`);
