// LEDGE — Smart Spend Intelligence for Solo Builders
// Inspired by: Midday.ai (featured on darkmodedesign.com) — "The business stack for modern founders"
//   + Land-book trending Cardless embedded credit platform
//   + Awwwards SOTD SUTÉRA's editorial minimalism (Mar 28, 2026)
// Theme: LIGHT — warm paper-white editorial, big typography, clarity-first data UX
// Generated by RAM Design Heartbeat — 2026-03-28

const fs = require('fs');

const W = 390, H = 844;
const PAD = 24;

const C = {
  bg:       '#F6F4F1',
  surface:  '#FFFFFF',
  border:   '#E8E4DD',
  text:     '#17150F',
  muted:    '#8A7F70',
  accent:   '#2952CC',
  accent2:  '#16A34A',
  warn:     '#D97706',
  red:      '#DC2626',
  dim:      '#F0EDE8',
  ink:      '#3D3A32',
};

function rect(x, y, w, h, fill, opts = {}) {
  return { type: 'RECTANGLE', x, y, width: w, height: h, fill, cornerRadius: opts.r || 0, opacity: opts.opacity || 1, stroke: opts.stroke || null, strokeWidth: opts.sw || 0 };
}

function text(content, x, y, opts = {}) {
  return { type: 'TEXT', x, y, content, fontSize: opts.size || 14, fontFamily: opts.font || 'Inter', fontWeight: opts.weight || '400', fill: opts.color || C.text, letterSpacing: opts.ls !== undefined ? opts.ls : -0.2, lineHeight: opts.lh || 1.3, width: opts.w || 300, align: opts.align || 'left', opacity: opts.opacity || 1 };
}

function line(x1, y1, x2, y2, color, opts = {}) {
  return { type: 'LINE', x: x1, y: y1, points: [{ x: 0, y: 0 }, { x: x2 - x1, y: y2 - y1 }], stroke: color, strokeWidth: opts.sw || 1, opacity: opts.opacity || 1 };
}

function pill(label, x, y, fill, textColor, opts = {}) {
  const w = opts.w || (label.length * 7 + 16);
  const h = opts.h || 22;
  return { type: 'GROUP', x, y, children: [ rect(0, 0, w, h, fill, { r: h / 2 }), text(label, 8, (h - 13) / 2 + 1, { size: 10, weight: '600', color: textColor, ls: 0.3, w: w - 16 }) ] };
}

function statusBar() {
  return { type: 'GROUP', x: 0, y: 0, children: [ rect(0, 0, W, 44, C.bg), text('9:41', PAD, 14, { size: 15, weight: '600', color: C.text, ls: 0, w: 60 }), text('●●●  ▲  ▌▌', W - PAD - 80, 14, { size: 11, weight: '500', color: C.ink, ls: 1.0, w: 80, align: 'right' }) ] };
}

function navBar(active) {
  const tabs = [ { label: 'Home', icon: '⌂', x: 0 }, { label: 'Txns', icon: '↔', x: 78 }, { label: 'Insights', icon: '◎', x: 156 }, { label: 'Invoice', icon: '▤', x: 243 }, { label: 'Reports', icon: '⊞', x: 321 } ];
  const items = [];
  tabs.forEach((tab, i) => {
    const isActive = i === active;
    items.push(
      rect(tab.x, 0, 69, 60, isActive ? C.surface : 'transparent'),
      text(tab.icon, tab.x + 23, 8, { size: 16, weight: '400', color: isActive ? C.accent : C.muted, w: 30, align: 'center' }),
      text(tab.label, tab.x + 5, 30, { size: 9, weight: isActive ? '700' : '400', color: isActive ? C.accent : C.muted, ls: 0.2, w: 60, align: 'center' }),
    );
    if (isActive) items.push(rect(tab.x + 18, 52, 34, 2, C.accent, { r: 1 }));
  });
  return { type: 'GROUP', x: 0, y: H - 72, children: [ rect(0, 0, W, 72, C.surface, { stroke: C.border, sw: 1 }), ...items ] };
}

function makeScreen(name, bg, children) {
  return { name, width: W, height: H, fill: bg, children };
}

function sparkBars(x, y, data, w, h, color) {
  const maxVal = Math.max(...data);
  const barW = Math.floor(w / data.length) - 2;
  return data.map((val, i) => {
    const barH = Math.max(3, Math.round((val / maxVal) * h));
    return rect(x + i * (barW + 2), y + (h - barH), barW, barH, color, { r: 2 });
  });
}

function trendLine(x, y, points, w, h, color, opts = {}) {
  const maxV = Math.max(...points), minV = Math.min(...points);
  const range = maxV - minV || 1;
  const stepX = w / (points.length - 1);
  const nodes = points.map((v, i) => ({ x: i * stepX, y: h - ((v - minV) / range) * h }));
  const items = [];
  for (let i = 0; i < nodes.length - 1; i++) {
    const a = nodes[i], b = nodes[i + 1];
    const len = Math.sqrt((b.x - a.x) ** 2 + (b.y - a.y) ** 2);
    const angle = Math.atan2(b.y - a.y, b.x - a.x) * (180 / Math.PI);
    items.push({ type: 'RECTANGLE', x: x + a.x, y: y + a.y, width: len, height: opts.sw || 2, fill: color, cornerRadius: 1, rotation: angle, opacity: 1 });
    items.push(rect(x + a.x, y + a.y, b.x - a.x, h - a.y, color, { opacity: 0.05 }));
  }
  return items;
}

// SCREEN 1: DASHBOARD
const screen1 = makeScreen('DASHBOARD — Cash Position', C.bg, [
  statusBar(),
  text('Good morning, Alex', PAD, 56, { size: 13, weight: '400', color: C.muted, ls: 0, w: 240 }),
  text('March 2026', PAD, 76, { size: 26, weight: '700', color: C.text, ls: -0.8, w: 280 }),
  { type: 'GROUP', x: W - PAD - 36, y: 68, children: [ rect(0, 0, 36, 36, C.surface, { r: 18, stroke: C.border, sw: 1 }), text('◔', 8, 9, { size: 16, color: C.ink, w: 22 }), rect(22, 0, 10, 10, C.accent, { r: 5 }), text('3', 24, 1, { size: 7, weight: '700', color: '#fff', w: 8 }) ] },
  { type: 'GROUP', x: PAD, y: 118, children: [
    rect(0, 0, W - PAD * 2, 148, C.accent, { r: 20 }),
    rect(0, 0, W - PAD * 2, 148, '#FFFFFF', { r: 20, opacity: 0.04 }),
    text('Current Balance', 20, 20, { size: 11, weight: '500', color: '#FFFFFF', ls: 0.5, w: 160, opacity: 0.7 }),
    text('$24,850', 20, 40, { size: 40, weight: '700', color: '#FFFFFF', ls: -1.5, w: 260 }),
    text('.32', 168, 48, { size: 20, weight: '400', color: '#FFFFFF', ls: -0.5, w: 60, opacity: 0.6 }),
    pill('+$1,240 this month', 20, 96, 'rgba(255,255,255,0.18)', '#fff', { w: 150, h: 24 }),
    ...sparkBars(W - PAD * 2 - 80, 90, [40, 55, 35, 60, 72, 58, 80], 72, 44, 'rgba(255,255,255,0.35)'),
    text('up 5.2% vs last month', 20, 126, { size: 10, weight: '400', color: '#FFFFFF', ls: 0, w: 200, opacity: 0.7 }),
  ] },
  { type: 'GROUP', x: PAD, y: 284, children: [
    rect(0, 0, (W - PAD * 2 - 10) / 2, 84, C.surface, { r: 16, stroke: C.border, sw: 1 }),
    text('Monthly Burn', 14, 14, { size: 10, weight: '500', color: C.muted, ls: 0.3, w: 120 }),
    text('$6,420', 14, 34, { size: 22, weight: '700', color: C.text, ls: -0.6, w: 140 }),
    text('down $380 vs Feb', 14, 62, { size: 10, weight: '400', color: C.accent2, ls: 0, w: 130 }),
  ] },
  { type: 'GROUP', x: PAD + (W - PAD * 2 - 10) / 2 + 10, y: 284, children: [
    rect(0, 0, (W - PAD * 2 - 10) / 2, 84, C.surface, { r: 16, stroke: C.border, sw: 1 }),
    text('Runway', 14, 14, { size: 10, weight: '500', color: C.muted, ls: 0.3, w: 120 }),
    text('3.8 mo', 14, 34, { size: 22, weight: '700', color: C.text, ls: -0.6, w: 140 }),
    text('If burn stays flat', 14, 62, { size: 10, weight: '400', color: C.muted, ls: 0, w: 120 }),
  ] },
  { type: 'GROUP', x: PAD, y: 384, children: [
    rect(0, 0, W - PAD * 2, 68, C.dim, { r: 14 }),
    rect(0, 0, 4, 68, C.accent2, { r: 2 }),
    text('Ledge saved you 4.5 hrs this month', 18, 12, { size: 12, weight: '600', color: C.text, ls: -0.2, w: 280 }),
    text('Auto-matched 38 receipts. No manual entry needed.', 18, 34, { size: 11, weight: '400', color: C.muted, ls: 0, w: 300, lh: 1.4 }),
  ] },
  text('Recent', PAD, 468, { size: 13, weight: '600', color: C.text, ls: -0.2, w: 80 }),
  text('See all', W - PAD - 50, 468, { size: 12, weight: '500', color: C.accent, ls: 0, w: 50 }),
  ...[
    { name: 'Figma', cat: 'Design Tools', date: 'Today', amount: '-$20.00', aColor: C.red, iColor: C.accent },
    { name: 'Stripe Payout', cat: 'Income', date: 'Yesterday', amount: '+$3,200', aColor: C.accent2, iColor: C.accent2 },
    { name: 'AWS', cat: 'Infrastructure', date: 'Mar 27', amount: '-$182.40', aColor: C.red, iColor: C.warn },
  ].map((tx, i) => ({
    type: 'GROUP', x: PAD, y: 490 + i * 60,
    children: [
      rect(0, 0, W - PAD * 2, 52, C.surface, { r: 12, stroke: C.border, sw: 1 }),
      rect(10, 12, 28, 28, C.dim, { r: 14 }),
      text('*', 18, 16, { size: 14, color: tx.iColor, w: 14 }),
      text(tx.name, 50, 12, { size: 13, weight: '600', color: C.text, ls: -0.2, w: 150 }),
      text(tx.cat + ' · ' + tx.date, 50, 30, { size: 10, weight: '400', color: C.muted, ls: 0, w: 150 }),
      text(tx.amount, W - PAD * 2 - 76, 18, { size: 13, weight: '600', color: tx.aColor, ls: 0, w: 74, align: 'right' }),
    ],
  })),
  navBar(0),
]);

// SCREEN 2: TRANSACTIONS
const screen2 = makeScreen('TRANSACTIONS — Smart Feed', C.bg, [
  statusBar(),
  text('Transactions', PAD, 56, { size: 24, weight: '700', color: C.text, ls: -0.7, w: 220 }),
  { type: 'GROUP', x: PAD, y: 92, children: [
    pill('All', 0, 0, C.accent, '#fff', { w: 44, h: 28 }),
    pill('Income', 52, 0, C.dim, C.ink, { w: 62, h: 28 }),
    pill('Expenses', 122, 0, C.dim, C.ink, { w: 70, h: 28 }),
    pill('Unmatched', 200, 0, '#FEF3C7', C.warn, { w: 82, h: 28 }),
  ] },
  { type: 'GROUP', x: PAD, y: 132, children: [
    rect(0, 0, W - PAD * 2, 40, C.surface, { r: 20, stroke: C.border, sw: 1 }),
    text('Search transactions...', 16, 12, { size: 13, weight: '400', color: C.muted, ls: 0, w: 250 }),
  ] },
  text('This Week', PAD, 186, { size: 11, weight: '600', color: C.muted, ls: 0.5, w: 120 }),
  text('-$280 net', W - PAD - 66, 186, { size: 11, weight: '400', color: C.red, ls: 0, w: 68, align: 'right' }),
  ...[
    { merchant: 'Linear', cat: 'Productivity', date: 'Mar 28', amount: '-$8.00', ac: C.red, matched: true },
    { merchant: 'Stripe Payout', cat: 'Income', date: 'Mar 27', amount: '+$3,200', ac: C.accent2, matched: true },
    { merchant: 'AWS', cat: 'Infrastructure', date: 'Mar 27', amount: '-$182.40', ac: C.red, matched: true },
    { merchant: 'Vercel', cat: 'Hosting', date: 'Mar 26', amount: '-$20.00', ac: C.red, matched: false },
    { merchant: 'Notion', cat: 'Tools', date: 'Mar 25', amount: '-$16.00', ac: C.red, matched: true },
    { merchant: 'OpenAI', cat: 'AI / APIs', date: 'Mar 24', amount: '-$54.12', ac: C.red, matched: true },
    { merchant: 'Acme Corp', cat: 'Invoice #041', date: 'Mar 22', amount: '+$4,800', ac: C.accent2, matched: true },
  ].map((tx, i) => ({
    type: 'GROUP', x: PAD, y: 208 + i * 62,
    children: [
      rect(0, 0, W - PAD * 2, 54, C.surface, { r: 12, stroke: C.border, sw: 1 }),
      rect(8, 10, 34, 34, tx.ac === C.accent2 ? '#EFF7EE' : C.dim, { r: 17 }),
      text(tx.merchant[0], 16, 18, { size: 14, weight: '700', color: tx.ac, w: 20 }),
      text(tx.merchant, 52, 10, { size: 13, weight: '600', color: C.text, ls: -0.2, w: 160 }),
      text(tx.cat + ' · ' + tx.date, 52, 28, { size: 10, color: C.muted, ls: 0, w: 160 }),
      text(tx.amount, W - PAD * 2 - 78, 16, { size: 13, weight: '600', color: tx.ac, ls: 0, w: 76, align: 'right' }),
      tx.matched ? text('matched', W - PAD * 2 - 66, 34, { size: 8, weight: '600', color: C.accent2, ls: 0.3, w: 64, align: 'right' }) : pill('unmatched', W - PAD * 2 - 72, 34, '#FEF3C7', C.warn, { w: 68, h: 14 }),
    ],
  })),
  navBar(1),
]);

// SCREEN 3: INSIGHTS
const screen3 = makeScreen('INSIGHTS — Monthly Trends', C.bg, [
  statusBar(),
  text('Insights', PAD, 56, { size: 24, weight: '700', color: C.text, ls: -0.7, w: 180 }),
  { type: 'GROUP', x: PAD, y: 92, children:
    ['Jan', 'Feb', 'Mar', 'Apr'].map((m, i) => ({
      type: 'GROUP', x: i * 78, y: 0,
      children: [
        rect(0, 0, 70, 28, m === 'Mar' ? C.text : 'transparent', { r: 14 }),
        text(m, 14, 6, { size: 12, weight: m === 'Mar' ? '700' : '400', color: m === 'Mar' ? '#fff' : C.muted, ls: 0.2, w: 44 }),
      ],
    }))
  },
  { type: 'GROUP', x: PAD, y: 136, children: [
    rect(0, 0, W - PAD * 2, 148, C.surface, { r: 18, stroke: C.border, sw: 1 }),
    text('Monthly Spend', 16, 14, { size: 11, weight: '600', color: C.muted, ls: 0.3, w: 140 }),
    text('$6,420', 16, 32, { size: 26, weight: '700', color: C.text, ls: -0.7, w: 150 }),
    text('down 5.6% vs Feb', 120, 42, { size: 10, weight: '500', color: C.accent2, ls: 0, w: 130 }),
    ...trendLine(16, 75, [5800, 6200, 7100, 6800, 6420, 6600, 6420], W - PAD * 2 - 32, 56, C.accent, { sw: 2 }),
    text('Jan', 16, 136, { size: 9, color: C.muted, ls: 0, w: 30 }),
    text('Feb', 74, 136, { size: 9, color: C.muted, ls: 0, w: 30 }),
    text('Mar', 132, 136, { size: 9, color: C.muted, ls: 0, w: 30, weight: '700' }),
    text('Apr', 200, 136, { size: 9, color: C.muted, ls: 0, w: 30 }),
  ] },
  text('Spend by Category', PAD, 300, { size: 13, weight: '600', color: C.text, ls: -0.2, w: 200 }),
  ...[
    { cat: 'Infrastructure', pct: 42, amt: '$2,697', color: C.accent },
    { cat: 'Tools & SaaS', pct: 28, amt: '$1,798', color: '#6366F1' },
    { cat: 'Marketing', pct: 18, amt: '$1,156', color: C.warn },
    { cat: 'Other', pct: 12, amt: '$770', color: C.muted },
  ].map((item, i) => ({
    type: 'GROUP', x: PAD, y: 324 + i * 60,
    children: [
      rect(0, 0, W - PAD * 2, 50, C.surface, { r: 12, stroke: C.border, sw: 1 }),
      rect(0, 0, 4, 50, item.color, { r: 2 }),
      text(item.cat, 16, 8, { size: 13, weight: '600', color: C.text, ls: -0.2, w: 160 }),
      text(item.pct + '%', 16, 28, { size: 11, color: C.muted, ls: 0, w: 60 }),
      rect(16, 42, W - PAD * 2 - 88, 4, C.dim, { r: 2 }),
      rect(16, 42, Math.round((W - PAD * 2 - 88) * item.pct / 100), 4, item.color, { r: 2 }),
      text(item.amt, W - PAD * 2 - 66, 12, { size: 13, weight: '600', color: C.text, ls: 0, w: 64, align: 'right' }),
    ],
  })),
  navBar(2),
]);

// SCREEN 4: INVOICING
const screen4 = makeScreen('INVOICING — Outstanding', C.bg, [
  statusBar(),
  text('Invoicing', PAD, 56, { size: 24, weight: '700', color: C.text, ls: -0.7, w: 200 }),
  { type: 'GROUP', x: PAD, y: 96, children: [
    rect(0, 0, W - PAD * 2, 72, C.surface, { r: 16, stroke: C.border, sw: 1 }),
    text('Awaiting', 20, 12, { size: 10, weight: '500', color: C.muted, ls: 0.3, w: 80 }),
    text('$4,800', 20, 30, { size: 20, weight: '700', color: C.warn, ls: -0.5, w: 100 }),
    text('1 invoice', 20, 54, { size: 9, color: C.muted, ls: 0, w: 80 }),
    rect((W - PAD * 2) / 2 - 1, 12, 1, 50, C.border),
    text('Draft', (W - PAD * 2) / 2 + 16, 12, { size: 10, weight: '500', color: C.muted, ls: 0.3, w: 80 }),
    text('$2,200', (W - PAD * 2) / 2 + 16, 30, { size: 20, weight: '700', color: C.ink, ls: -0.5, w: 100 }),
    text('1 invoice', (W - PAD * 2) / 2 + 16, 54, { size: 9, color: C.muted, ls: 0, w: 80 }),
  ] },
  { type: 'GROUP', x: PAD, y: 180, children: [
    rect(0, 0, W - PAD * 2, 48, C.accent, { r: 24 }),
    text('+ Create Invoice', (W - PAD * 2) / 2 - 65, 14, { size: 15, weight: '700', color: '#fff', ls: -0.2, w: 140, align: 'center' }),
  ] },
  text('All Invoices', PAD, 244, { size: 13, weight: '600', color: C.text, ls: -0.2, w: 140 }),
  ...[
    { client: 'Acme Corp', amount: '$4,800', due: 'Due Mar 31', status: 'Sent', sc: C.warn, sb: '#FEF3C7' },
    { client: 'Bravo Labs', amount: '$2,200', due: 'Due Apr 5', status: 'Draft', sc: C.muted, sb: C.dim },
    { client: 'Crux Studio', amount: '$6,500', due: 'Paid Mar 22', status: 'Paid', sc: C.accent2, sb: '#EFF7EE' },
  ].map((inv, i) => ({
    type: 'GROUP', x: PAD, y: 268 + i * 84,
    children: [
      rect(0, 0, W - PAD * 2, 74, C.surface, { r: 16, stroke: C.border, sw: 1 }),
      rect(14, 16, 42, 42, C.dim, { r: 21 }),
      text(inv.client[0], 26, 28, { size: 16, weight: '700', color: C.ink, w: 22 }),
      text(inv.client, 68, 14, { size: 14, weight: '600', color: C.text, ls: -0.2, w: 150 }),
      text(inv.due, 68, 34, { size: 11, color: C.muted, ls: 0, w: 140 }),
      text(inv.amount, W - PAD * 2 - 70, 14, { size: 16, weight: '700', color: C.text, ls: -0.3, w: 68, align: 'right' }),
      pill(inv.status, W - PAD * 2 - 56, 42, inv.sb, inv.sc, { w: 50, h: 20 }),
    ],
  })),
  { type: 'GROUP', x: PAD, y: 540, children: [
    rect(0, 0, W - PAD * 2, 68, C.dim, { r: 14 }),
    text('Invoice template auto-fills from past work', 16, 10, { size: 12, weight: '600', color: C.text, ls: -0.2, w: 300 }),
    text('Client name, rate, line items pre-filled. Edit and send in 30s.', 16, 30, { size: 10, weight: '400', color: C.muted, ls: 0, w: 310, lh: 1.4 }),
  ] },
  navBar(3),
]);

// SCREEN 5: REPORTS
const screen5 = makeScreen('REPORTS — Accounting Export', C.bg, [
  statusBar(),
  text('Reports', PAD, 56, { size: 24, weight: '700', color: C.text, ls: -0.7, w: 180 }),
  { type: 'GROUP', x: PAD, y: 94, children: [
    rect(0, 0, W - PAD * 2, 40, C.surface, { r: 20, stroke: C.border, sw: 1 }),
    text('Q1 2026', (W - PAD * 2) / 2 - 40, 12, { size: 13, weight: '600', color: C.text, ls: -0.2, w: 80, align: 'center' }),
  ] },
  { type: 'GROUP', x: PAD, y: 148, children: [
    rect(0, 0, W - PAD * 2, 116, C.surface, { r: 18, stroke: C.border, sw: 1 }),
    text('Q1 Profit & Loss', 16, 14, { size: 11, weight: '600', color: C.muted, ls: 0.4, w: 160 }),
    text('$11,530', 16, 34, { size: 32, weight: '700', color: C.text, ls: -1.0, w: 200 }),
    text('net profit', 148, 46, { size: 12, weight: '400', color: C.muted, ls: 0, w: 80 }),
    line(16, 82, W - PAD * 2 - 16, 82, C.border),
    text('Revenue', 16, 90, { size: 11, color: C.muted, ls: 0, w: 80 }),
    text('$28,600', W - PAD * 2 - 70, 90, { size: 12, weight: '600', color: C.accent2, ls: 0, w: 68, align: 'right' }),
    text('Expenses', 16, 106, { size: 11, color: C.muted, ls: 0, w: 80 }),
    text('-$17,070', W - PAD * 2 - 70, 106, { size: 12, weight: '600', color: C.red, ls: 0, w: 68, align: 'right' }),
  ] },
  text('Export', PAD, 282, { size: 13, weight: '600', color: C.text, ls: -0.2, w: 80 }),
  ...[
    { label: 'CSV  — All transactions', desc: 'Excel and Google Sheets ready', color: C.accent },
    { label: 'PDF  — P&L Statement', desc: 'Accountant-friendly summary', color: '#6366F1' },
    { label: 'JSON — Raw data export', desc: 'For your own automation', color: C.warn },
  ].map((item, i) => ({
    type: 'GROUP', x: PAD, y: 306 + i * 72,
    children: [
      rect(0, 0, W - PAD * 2, 62, C.surface, { r: 14, stroke: C.border, sw: 1 }),
      rect(12, 12, 38, 38, item.color + '20', { r: 19 }),
      text('>', 22, 22, { size: 14, color: item.color, w: 16 }),
      text(item.label, 62, 10, { size: 13, weight: '600', color: C.text, ls: -0.2, w: 200 }),
      text(item.desc, 62, 30, { size: 10, color: C.muted, ls: 0, w: 200 }),
      text('->', W - PAD * 2 - 24, 22, { size: 13, color: C.muted, w: 18 }),
    ],
  })),
  { type: 'GROUP', x: PAD, y: 526, children: [
    rect(0, 0, W - PAD * 2, 68, C.dim, { r: 14 }),
    rect(0, 0, 4, 68, C.accent, { r: 2 }),
    text('Share with your accountant', 18, 10, { size: 12, weight: '600', color: C.text, ls: -0.2, w: 280 }),
    text('Read-only link. They see clean data, no Ledge login needed.', 18, 30, { size: 10, weight: '400', color: C.muted, ls: 0, w: 310, lh: 1.4 }),
  ] },
  { type: 'GROUP', x: PAD, y: 608, children: [
    rect(0, 0, W - PAD * 2, 52, '#FEF3C7', { r: 14 }),
    text('Estimated Q1 Tax Due: $2,882', 14, 10, { size: 12, weight: '600', color: C.warn, ls: -0.2, w: 280 }),
    text('Set aside now. Based on 25% effective rate. Not financial advice.', 14, 28, { size: 9, weight: '400', color: C.warn, ls: 0, w: 300, opacity: 0.8 }),
  ] },
  navBar(4),
]);

// BUILD
const pen = {
  version: '2.8',
  name: 'LEDGE — Smart Spend Intelligence',
  width: W,
  height: H,
  fill: C.bg,
  screens: [screen1, screen2, screen3, screen4, screen5],
};

fs.writeFileSync('ledge.pen', JSON.stringify(pen, null, 2));
console.log('✓ ledge.pen written —', Math.round(fs.statSync('ledge.pen').size / 1024) + 'KB');
console.log('  Screens:', pen.screens.map(s => s.name));
