// VEGA — Agent Orchestration Console
// Inspired by: Linear.app's "product system for teams and agents" + Lapa.ninja Paperclip "zero-human companies"
// Theme: DARK — ultra-dark like Linear (#08090A), tight Inter tracking, glassmorphism card edges
// Generated by RAM Design Heartbeat — 2026-03-28

const fs = require('fs');

const W = 390, H = 844;
const PAD = 24;

// VEGA Palette — Ultra-dark agent console
const C = {
  bg:       '#080C14',  // near-black with slight navy cast
  surface:  '#0F1521',  // card bg
  border:   '#1E2A3D',  // subtle borders
  text:     '#E6EDF8',  // near-white
  muted:    '#5C6B82',  // muted text
  accent:   '#4F87FF',  // electric blue — agent active
  accent2:  '#00E5A0',  // emerald green — success/online
  warn:     '#FF6B3D',  // amber-red — warning
  red:      '#FF4466',  // alert red
  dim:      '#1A2535',  // dimmer surface
};

function rect(x, y, w, h, fill, opts = {}) {
  return {
    type: 'RECTANGLE',
    x, y, width: w, height: h,
    fill,
    cornerRadius: opts.r || 0,
    opacity: opts.opacity || 1,
    stroke: opts.stroke || null,
    strokeWidth: opts.sw || 0,
  };
}

function text(content, x, y, opts = {}) {
  return {
    type: 'TEXT',
    x, y,
    content,
    fontSize: opts.size || 14,
    fontFamily: opts.font || 'Inter',
    fontWeight: opts.weight || '400',
    fill: opts.color || C.text,
    letterSpacing: opts.ls || -0.2,
    lineHeight: opts.lh || 1.3,
    width: opts.w || 300,
    align: opts.align || 'left',
    opacity: opts.opacity || 1,
  };
}

function pill(label, x, y, fillColor, textColor, opts = {}) {
  const w = opts.w || (label.length * 7 + 16);
  const h = opts.h || 22;
  return {
    type: 'GROUP',
    x, y,
    children: [
      rect(0, 0, w, h, fillColor, { r: 11 }),
      text(label, w/2, h/2 - 6, { size: 10, weight: '600', color: textColor, ls: 0.4, align: 'center', w: w }),
    ]
  };
}

// ─── STATUS DOT ───────────────────────────────────────────
function dot(x, y, color) {
  return { type: 'ELLIPSE', x, y, width: 8, height: 8, fill: color };
}

// ─── AGENT CARD ───────────────────────────────────────────
function agentCard(x, y, agent) {
  const W_CARD = W - PAD * 2;
  const H_CARD = 80;
  const statusColor = agent.status === 'online' ? C.accent2 : agent.status === 'busy' ? C.accent : agent.status === 'warning' ? C.warn : C.red;
  const statusLabel = agent.status.toUpperCase();

  return {
    type: 'GROUP',
    x, y,
    children: [
      rect(0, 0, W_CARD, H_CARD, C.surface, { r: 12, stroke: C.border, sw: 1 }),
      // left accent stripe
      rect(0, 0, 3, H_CARD, statusColor, { r: 12 }),
      rect(0, H_CARD/2, 3, H_CARD/2, statusColor),
      // Status dot
      dot(16, 16, statusColor),
      // Agent name
      text(agent.name, 32, 13, { size: 13, weight: '600', color: C.text, ls: -0.3, w: 180 }),
      // Model tag
      text(agent.model, 32, 30, { size: 10, weight: '400', color: C.muted, ls: 0.1, w: 140 }),
      // Tasks completed
      text(`${agent.tasks} tasks`, W_CARD - 80, 13, { size: 12, weight: '500', color: C.text, ls: -0.2, w: 70, align: 'right' }),
      // Latency
      text(`${agent.latency}ms avg`, W_CARD - 80, 30, { size: 10, weight: '400', color: C.muted, ls: 0, w: 70, align: 'right' }),
      // Status pill
      pill(statusLabel, W_CARD - 72, H_CARD - 30, statusColor + '22', statusColor, { w: 60, h: 20 }),
      // Action count bar bg
      rect(12, H_CARD - 18, W_CARD - 90, 4, C.border, { r: 2 }),
      // Action count bar fill
      rect(12, H_CARD - 18, Math.round((W_CARD - 90) * agent.progress), 4, statusColor, { r: 2 }),
    ]
  };
}

// ─── PIPELINE NODE ────────────────────────────────────────
function pipelineNode(x, y, label, sublabel, color, opts = {}) {
  const W_NODE = opts.w || 110;
  const H_NODE = 56;
  return {
    type: 'GROUP',
    x, y,
    children: [
      rect(0, 0, W_NODE, H_NODE, C.surface, { r: 10, stroke: color + '55', sw: 1 }),
      rect(0, 0, W_NODE, 3, color, { r: 3 }),
      text(label, 10, 12, { size: 11, weight: '600', color: C.text, ls: -0.2, w: W_NODE - 20 }),
      text(sublabel, 10, 28, { size: 9, weight: '400', color: C.muted, ls: 0, w: W_NODE - 20 }),
      dot(W_NODE - 16, H_NODE - 14, color),
    ]
  };
}

function connector(x1, y1, x2, y2) {
  return {
    type: 'LINE',
    x: x1, y: y1,
    x2: x2, y2: y2,
    stroke: C.border,
    strokeWidth: 1.5,
    strokeDash: [4, 3],
  };
}

// ─── NAV BAR ──────────────────────────────────────────────
function navBar(activeIdx) {
  const items = [
    { icon: '⬡', label: 'Fleet' },
    { icon: '⬢', label: 'Flows' },
    { icon: '◈', label: 'Monitor' },
    { icon: '⊕', label: 'Deploy' },
    { icon: '⊙', label: 'Settings' },
  ];
  const NAV_H = 64;
  const itemW = W / items.length;

  return {
    type: 'GROUP',
    x: 0, y: H - NAV_H,
    children: [
      rect(0, 0, W, NAV_H, C.surface, { stroke: C.border, sw: 0.5 }),
      // top line
      rect(0, 0, W, 1, C.border),
      ...items.flatMap((item, i) => {
        const isActive = i === activeIdx;
        const cx = itemW * i + itemW / 2;
        return [
          text(item.icon, cx - 8, 10, { size: 18, color: isActive ? C.accent : C.muted, w: 20, align: 'center' }),
          text(item.label, cx - 20, 33, { size: 10, weight: isActive ? '600' : '400', color: isActive ? C.accent : C.muted, w: 42, align: 'center' }),
          ...(isActive ? [rect(cx - 16, -1, 32, 2, C.accent, { r: 1 })] : []),
        ];
      }),
    ]
  };
}

// ─── STATUS BAR ───────────────────────────────────────────
function statusBar(time = '09:41') {
  return {
    type: 'GROUP',
    x: 0, y: 0,
    children: [
      rect(0, 0, W, 44, C.bg),
      text(time, PAD, 14, { size: 15, weight: '600', color: C.text, ls: -0.3, w: 80 }),
      text('●●●', W - 80, 14, { size: 11, color: C.text, w: 70, align: 'right' }),
    ]
  };
}

// ─── SCREEN BUILDER ────────────────────────────────────────
function makeScreen(name, fill, children) {
  return {
    name,
    width: W,
    height: H,
    fill,
    children: [
      rect(0, 0, W, H, fill),
      ...children,
    ]
  };
}

// ══════════════════════════════════════════════
// SCREEN 1: FLEET — Agent Roster
// ══════════════════════════════════════════════
const screen1 = makeScreen('FLEET — Agent Roster', C.bg, [
  statusBar(),
  // Header
  text('Agent Fleet', PAD, 56, { size: 26, weight: '700', color: C.text, ls: -0.8, w: 200 }),
  text('12 active · 3 paused · 1 incident', PAD, 86, { size: 13, weight: '400', color: C.muted, ls: -0.1, w: 260 }),
  // Summary pills row
  {
    type: 'GROUP', x: PAD, y: 110,
    children: [
      // Online
      rect(0, 0, 72, 28, C.accent2 + '18', { r: 14, stroke: C.accent2 + '44', sw: 1 }),
      text('12 online', 10, 7, { size: 10, weight: '600', color: C.accent2, ls: 0.2, w: 60 }),
      // Busy
      rect(80, 0, 60, 28, C.accent + '18', { r: 14, stroke: C.accent + '44', sw: 1 }),
      text('4 busy', 90, 7, { size: 10, weight: '600', color: C.accent, ls: 0.2, w: 48 }),
      // Warning
      rect(148, 0, 72, 28, C.warn + '18', { r: 14, stroke: C.warn + '44', sw: 1 }),
      text('1 alert', 158, 7, { size: 10, weight: '600', color: C.warn, ls: 0.2, w: 60 }),
    ]
  },
  // Agent cards
  agentCard(PAD, 156, { name: 'Orion', model: 'claude-3-7-sonnet', tasks: 847, latency: 312, status: 'online', progress: 0.82 }),
  agentCard(PAD, 248, { name: 'Atlas', model: 'gpt-4o-mini', tasks: 1204, latency: 178, status: 'busy', progress: 0.61 }),
  agentCard(PAD, 340, { name: 'Lyra', model: 'gemini-2.0-flash', tasks: 390, latency: 220, status: 'online', progress: 0.45 }),
  agentCard(PAD, 432, { name: 'Cygnus', model: 'claude-3-haiku', tasks: 2810, latency: 98, status: 'online', progress: 0.94 }),
  agentCard(PAD, 524, { name: 'Vela', model: 'mistral-large', tasks: 62, latency: 445, status: 'warning', progress: 0.23 }),
  agentCard(PAD, 616, { name: 'Rigel', model: 'llama-3.3-70b', tasks: 18, latency: 890, status: 'offline', progress: 0.07 }),
  // Footer hint
  text('Tap agent to inspect · Swipe to pause', W/2 - 100, 714, { size: 11, color: C.muted, ls: 0, w: 220, align: 'center' }),
  navBar(0),
]);

// ══════════════════════════════════════════════
// SCREEN 2: FLOWS — Pipeline Visualization
// ══════════════════════════════════════════════
const screen2 = makeScreen('FLOWS — Pipeline', C.bg, [
  statusBar(),
  // Header
  text('Active Pipelines', PAD, 56, { size: 24, weight: '700', color: C.text, ls: -0.7, w: 260 }),
  text('Real-time agent workflows', PAD, 84, { size: 12, weight: '400', color: C.muted, ls: 0, w: 240 }),
  // Pipeline tabs
  {
    type: 'GROUP', x: PAD, y: 108,
    children: [
      rect(0, 0, 100, 28, C.accent, { r: 14 }),
      text('Customer', 10, 7, { size: 11, weight: '600', color: '#FFF', ls: 0, w: 86, align: 'center' }),
      rect(108, 0, 80, 28, C.surface, { r: 14, stroke: C.border, sw: 1 }),
      text('DevOps', 118, 7, { size: 11, weight: '400', color: C.muted, ls: 0, w: 66, align: 'center' }),
      rect(196, 0, 70, 28, C.surface, { r: 14, stroke: C.border, sw: 1 }),
      text('Finance', 206, 7, { size: 11, weight: '400', color: C.muted, ls: 0, w: 56, align: 'center' }),
    ]
  },
  // Pipeline section label
  text('INTAKE → TRIAGE → RESOLVE', PAD, 150, { size: 9, weight: '600', color: C.muted, ls: 1.5, w: 280 }),

  // Pipeline row 1: nodes + connectors
  pipelineNode(PAD, 166, 'Intake', '23 items/hr', C.accent2, { w: 100 }),
  connector(PAD + 100, 194, PAD + 130, 194),
  pipelineNode(PAD + 130, 166, 'Classifier', 'Orion', C.accent, { w: 100 }),
  connector(PAD + 230, 194, PAD + 260, 194),
  pipelineNode(PAD + 260, 166, 'Resolver', 'Atlas', C.accent2, { w: 82 }),

  // Sub-pipeline row
  text('ESCALATION BRANCH', PAD, 244, { size: 9, weight: '600', color: C.muted, ls: 1.5, w: 280 }),
  pipelineNode(PAD + 130, 258, 'Escalate', 'Low priority', C.warn, { w: 100 }),
  connector(PAD + 180, 222, PAD + 180, 258),

  // Pipeline row 2
  text('REVIEW → INVOICE → CLOSE', PAD, 340, { size: 9, weight: '600', color: C.muted, ls: 1.5, w: 280 }),
  pipelineNode(PAD, 356, 'Reviewer', 'Lyra', C.accent, { w: 100 }),
  connector(PAD + 100, 384, PAD + 130, 384),
  pipelineNode(PAD + 130, 356, 'Invoicer', 'Cygnus', C.accent2, { w: 100 }),
  connector(PAD + 230, 384, PAD + 260, 384),
  pipelineNode(PAD + 260, 356, 'Closer', 'Lyra', C.accent2, { w: 82 }),

  // Stats row
  {
    type: 'GROUP', x: PAD, y: 444,
    children: [
      rect(0, 0, W - PAD*2, 90, C.surface, { r: 12, stroke: C.border, sw: 1 }),
      text('Pipeline Health', 16, 14, { size: 12, weight: '600', color: C.text, ls: -0.2, w: 200 }),
      // Stat items
      text('Throughput', 16, 36, { size: 10, color: C.muted, ls: 0, w: 80 }),
      text('1,847 / hr', 16, 51, { size: 16, weight: '700', color: C.accent2, ls: -0.5, w: 100 }),
      text('Error rate', 130, 36, { size: 10, color: C.muted, ls: 0, w: 80 }),
      text('0.12%', 130, 51, { size: 16, weight: '700', color: C.accent, ls: -0.5, w: 80 }),
      text('Avg latency', 230, 36, { size: 10, color: C.muted, ls: 0, w: 80 }),
      text('284ms', 230, 51, { size: 16, weight: '700', color: C.text, ls: -0.5, w: 80 }),
    ]
  },

  // Incident banner
  {
    type: 'GROUP', x: PAD, y: 550,
    children: [
      rect(0, 0, W - PAD*2, 48, C.warn + '18', { r: 10, stroke: C.warn + '55', sw: 1 }),
      rect(0, 0, 3, 48, C.warn, { r: 3 }),
      text('⚠', 14, 14, { size: 16, color: C.warn, w: 20 }),
      text('Vela agent retry loop detected', 38, 12, { size: 12, weight: '600', color: C.warn, ls: -0.2, w: 220 }),
      text('3 retries in 90s — auto-paused', 38, 28, { size: 10, color: C.warn, ls: 0, w: 220, opacity: 0.8 }),
      text('View →', W - PAD*2 - 50, 18, { size: 11, weight: '600', color: C.warn, ls: 0, w: 44, align: 'right' }),
    ]
  },

  navBar(1),
]);

// ══════════════════════════════════════════════
// SCREEN 3: MONITOR — Agent Detail (Orion)
// ══════════════════════════════════════════════
const screen3 = makeScreen('MONITOR — Agent Detail', C.bg, [
  statusBar(),
  // Back + title
  text('← Fleet', PAD, 52, { size: 13, weight: '500', color: C.accent, ls: -0.1, w: 80 }),
  // Agent identity
  {
    type: 'GROUP', x: PAD, y: 76,
    children: [
      rect(0, 0, 52, 52, C.accent + '22', { r: 16, stroke: C.accent + '66', sw: 1 }),
      text('⬡', 13, 12, { size: 26, color: C.accent, w: 28 }),
      text('Orion', 62, 6, { size: 22, weight: '700', color: C.text, ls: -0.6, w: 180 }),
      text('claude-3-7-sonnet · online', 62, 32, { size: 11, weight: '400', color: C.muted, ls: 0, w: 200 }),
    ]
  },
  // Metric strip
  {
    type: 'GROUP', x: PAD, y: 148,
    children: [
      rect(0, 0, W - PAD*2, 1, C.border),
      // 3 metrics
      text('847', 0, 14, { size: 28, weight: '700', color: C.text, ls: -1, w: 90 }),
      text('Tasks today', 0, 46, { size: 10, color: C.muted, ls: 0, w: 90 }),
      text('312ms', 120, 14, { size: 28, weight: '700', color: C.accent2, ls: -1, w: 110 }),
      text('Avg latency', 120, 46, { size: 10, color: C.muted, ls: 0, w: 90 }),
      text('99.2%', 240, 14, { size: 28, weight: '700', color: C.accent, ls: -1, w: 90 }),
      text('Uptime', 240, 46, { size: 10, color: C.muted, ls: 0, w: 70 }),
      rect(0, 66, W - PAD*2, 1, C.border),
    ]
  },
  // Activity chart placeholder
  text('ACTIVITY — LAST 24H', PAD, 236, { size: 9, weight: '600', color: C.muted, ls: 1.5, w: 200 }),
  {
    type: 'GROUP', x: PAD, y: 254,
    children: [
      rect(0, 0, W - PAD*2, 80, C.surface, { r: 10, stroke: C.border, sw: 1 }),
      // Fake bar chart — activity bars
      ...[0.4, 0.6, 0.8, 0.7, 0.5, 0.9, 1.0, 0.85, 0.7, 0.6, 0.75, 0.9, 0.95, 0.8, 0.65, 0.7, 0.85, 0.78, 0.6, 0.9, 0.95, 0.88, 0.72, 0.8].map((h, i) => {
        const barH = Math.round(h * 52);
        const barW = 11;
        const x = 12 + i * 13.5;
        return rect(x, 66 - barH, barW, barH, i === 23 ? C.accent : C.accent + '55', { r: 2 });
      }),
    ]
  },
  // Recent actions list
  text('RECENT ACTIONS', PAD, 352, { size: 9, weight: '600', color: C.muted, ls: 1.5, w: 200 }),
  ...[
    { time: '09:41', action: 'Classified 14 support tickets', type: 'classify', color: C.accent },
    { time: '09:38', action: 'Drafted resolution for #8821', type: 'generate', color: C.accent2 },
    { time: '09:35', action: 'Escalated #8819 — sentiment neg', type: 'escalate', color: C.warn },
    { time: '09:31', action: 'Resolved 7 tier-1 requests', type: 'resolve', color: C.accent2 },
    { time: '09:28', action: 'Context window reset · resumed', type: 'system', color: C.muted },
  ].map((item, i) => ({
    type: 'GROUP', x: PAD, y: 372 + i * 54,
    children: [
      rect(0, 0, W - PAD*2, 46, C.surface, { r: 8, stroke: C.border, sw: 0.5 }),
      rect(0, 14, 3, 18, item.color, { r: 1 }),
      text(item.time, 12, 10, { size: 10, weight: '500', color: C.muted, ls: 0, w: 50 }),
      text(item.action, 12, 26, { size: 11, weight: '400', color: C.text, ls: -0.1, w: W - PAD*2 - 24 }),
    ]
  })),
  navBar(2),
]);

// ══════════════════════════════════════════════
// SCREEN 4: DEPLOY — Launch New Agent
// ══════════════════════════════════════════════
const screen4 = makeScreen('DEPLOY — Launch Agent', C.bg, [
  statusBar(),
  text('Deploy Agent', PAD, 56, { size: 24, weight: '700', color: C.text, ls: -0.7, w: 240 }),
  text('Configure and launch a new autonomous agent', PAD, 84, { size: 12, weight: '400', color: C.muted, ls: 0, w: 280 }),

  // Form card
  {
    type: 'GROUP', x: PAD, y: 110,
    children: [
      rect(0, 0, W - PAD*2, 440, C.surface, { r: 16, stroke: C.border, sw: 1 }),
      // Agent name field
      text('AGENT NAME', 16, 20, { size: 9, weight: '600', color: C.muted, ls: 1.5, w: 160 }),
      rect(16, 38, W - PAD*2 - 32, 40, C.bg, { r: 8, stroke: C.border, sw: 1 }),
      text('e.g. Cassiopeia', 28, 52, { size: 13, color: C.muted, ls: -0.1, w: 220 }),
      // Model field
      text('BASE MODEL', 16, 96, { size: 9, weight: '600', color: C.muted, ls: 1.5, w: 160 }),
      rect(16, 114, W - PAD*2 - 32, 40, C.bg, { r: 8, stroke: C.accent + '88', sw: 1 }),
      text('claude-3-7-sonnet', 28, 128, { size: 13, color: C.text, ls: -0.1, w: 200 }),
      text('▾', W - PAD*2 - 36, 128, { size: 14, color: C.muted, w: 14 }),
      // Role field
      text('ROLE / SYSTEM PROMPT', 16, 172, { size: 9, weight: '600', color: C.muted, ls: 1.5, w: 200 }),
      rect(16, 190, W - PAD*2 - 32, 80, C.bg, { r: 8, stroke: C.border, sw: 1 }),
      text('You are a customer support specialist...', 28, 202, { size: 12, color: C.muted, ls: 0, w: 260, lh: 1.5 }),
      // Permissions toggles
      text('PERMISSIONS', 16, 284, { size: 9, weight: '600', color: C.muted, ls: 1.5, w: 160 }),
      // Toggle items
      ...[
        { label: 'Send emails', value: true },
        { label: 'Access CRM', value: true },
        { label: 'Escalate to human', value: true },
        { label: 'Charge payment', value: false },
      ].map((t, i) => ({
        type: 'GROUP', x: 16, y: 302 + i * 28,
        children: [
          text(t.label, 0, 6, { size: 12, color: C.text, ls: -0.1, w: 160 }),
          rect(W - PAD*2 - 52, 0, 36, 20, t.value ? C.accent : C.border, { r: 10 }),
          { type: 'ELLIPSE', x: t.value ? W - PAD*2 - 22 : W - PAD*2 - 50, y: 2, width: 16, height: 16, fill: '#FFF' },
        ]
      })),
    ]
  },

  // Deploy button
  {
    type: 'GROUP', x: PAD, y: 568,
    children: [
      rect(0, 0, W - PAD*2, 52, C.accent, { r: 14 }),
      text('Deploy Agent', (W - PAD*2)/2 - 60, 17, { size: 16, weight: '700', color: '#FFF', ls: -0.3, w: 130, align: 'center' }),
    ]
  },
  text('Agent will start in sandbox mode · approve for production', W/2 - 150, 632, { size: 10, color: C.muted, ls: 0, w: 310, align: 'center' }),
  navBar(3),
]);

// ══════════════════════════════════════════════
// SCREEN 5: INCIDENT — Alert Feed
// ══════════════════════════════════════════════
const screen5 = makeScreen('INCIDENT — Alert Feed', C.bg, [
  statusBar(),
  text('Incidents', PAD, 56, { size: 24, weight: '700', color: C.text, ls: -0.7, w: 220 }),
  // Alert badge
  {
    type: 'GROUP', x: W - PAD - 42, y: 54,
    children: [
      rect(0, 0, 38, 24, C.red + '22', { r: 12, stroke: C.red + '66', sw: 1 }),
      text('1 crit', 5, 6, { size: 10, weight: '700', color: C.red, ls: 0.2, w: 30 }),
    ]
  },
  text('System · Today', PAD, 84, { size: 12, weight: '400', color: C.muted, ls: 0, w: 200 }),

  // Critical incident
  {
    type: 'GROUP', x: PAD, y: 110,
    children: [
      rect(0, 0, W - PAD*2, 120, C.red + '10', { r: 14, stroke: C.red + '55', sw: 1 }),
      rect(0, 0, 3, 120, C.red, { r: 3 }),
      { type: 'ELLIPSE', x: 16, y: 14, width: 10, height: 10, fill: C.red },
      text('CRITICAL', 34, 13, { size: 10, weight: '700', color: C.red, ls: 1.0, w: 80 }),
      text('09:41', W - PAD*2 - 44, 13, { size: 10, color: C.muted, ls: 0, w: 40, align: 'right' }),
      text('Vela — infinite retry loop', 16, 34, { size: 14, weight: '700', color: C.text, ls: -0.3, w: 280 }),
      text('Agent entered retry loop on task #9041. Invocation count exceeded threshold (3 retries / 90s). Auto-paused to prevent runaway spend.', 16, 56, { size: 11, weight: '400', color: C.muted, ls: 0, w: 310, lh: 1.5 }),
      // Action buttons
      rect(16, 94, 88, 18, C.red + '22', { r: 9 }),
      text('Inspect Agent', 22, 98, { size: 9, weight: '600', color: C.red, ls: 0.2, w: 80 }),
      rect(112, 94, 70, 18, C.surface, { r: 9, stroke: C.border, sw: 1 }),
      text('Dismiss', 118, 98, { size: 9, weight: '400', color: C.muted, ls: 0, w: 60 }),
    ]
  },

  // Warning incident
  {
    type: 'GROUP', x: PAD, y: 248,
    children: [
      rect(0, 0, W - PAD*2, 96, C.warn + '10', { r: 12, stroke: C.warn + '44', sw: 1 }),
      rect(0, 0, 3, 96, C.warn, { r: 3 }),
      text('WARNING', 16, 13, { size: 10, weight: '700', color: C.warn, ls: 1.0, w: 80 }),
      text('09:28', W - PAD*2 - 44, 13, { size: 10, color: C.muted, ls: 0, w: 40, align: 'right' }),
      text('Atlas — high token usage spike', 16, 32, { size: 14, weight: '600', color: C.text, ls: -0.3, w: 280 }),
      text('3.2× normal token usage detected. Reviewing prompt injection risk.', 16, 52, { size: 11, color: C.muted, ls: 0, w: 300, lh: 1.5 }),
    ]
  },

  // Info incidents
  {
    type: 'GROUP', x: PAD, y: 362,
    children: [
      rect(0, 0, W - PAD*2, 76, C.accent + '08', { r: 10, stroke: C.border, sw: 1 }),
      text('INFO', 16, 13, { size: 10, weight: '600', color: C.accent, ls: 1.0, w: 60 }),
      text('09:15', W - PAD*2 - 44, 13, { size: 10, color: C.muted, ls: 0, w: 40, align: 'right' }),
      text('Fleet auto-scaled — 2 agents cloned', 16, 32, { size: 13, weight: '500', color: C.text, ls: -0.2, w: 280 }),
      text('Load increase triggered Cygnus × 2 clone event.', 16, 50, { size: 11, color: C.muted, ls: 0, w: 280 }),
    ]
  },

  {
    type: 'GROUP', x: PAD, y: 454,
    children: [
      rect(0, 0, W - PAD*2, 76, C.accent2 + '08', { r: 10, stroke: C.border, sw: 1 }),
      text('RESOLVED', 16, 13, { size: 10, weight: '600', color: C.accent2, ls: 1.0, w: 90 }),
      text('08:55', W - PAD*2 - 44, 13, { size: 10, color: C.muted, ls: 0, w: 40, align: 'right' }),
      text('Orion context window reset', 16, 32, { size: 13, weight: '500', color: C.text, ls: -0.2, w: 280 }),
      text('Cleared and resumed without data loss. Checkpoint saved.', 16, 50, { size: 11, color: C.muted, ls: 0, w: 280 }),
    ]
  },

  // Resolve all button  
  {
    type: 'GROUP', x: PAD, y: 548,
    children: [
      rect(0, 0, W - PAD*2, 44, C.surface, { r: 12, stroke: C.border, sw: 1 }),
      text('View full audit log →', (W-PAD*2)/2 - 70, 13, { size: 13, weight: '500', color: C.muted, ls: -0.1, w: 150, align: 'center' }),
    ]
  },

  navBar(2),
]);

// ══════════════════════════════════════════════
// BUILD PEN FILE
// ══════════════════════════════════════════════
const pen = {
  version: '2.8',
  name: 'VEGA — Agent Orchestration Console',
  width: W,
  height: H,
  fill: C.bg,
  screens: [screen1, screen2, screen3, screen4, screen5],
};

fs.writeFileSync('vega.pen', JSON.stringify(pen, null, 2));
console.log('✓ vega.pen written —', Math.round(fs.statSync('vega.pen').size / 1024) + 'KB');
console.log('  Screens:', pen.screens.map(s => s.name));
